export const SUN_PRESET_OPTIONS = [
  {
    id: "realistic",
    label: "Realistic",
    distance: 175,
    visualRadius: 0.82,
    directionalLightBase: 4.0,
    ambientIntensity: 0.45,
    toneMappingExposure: 1.15,
    earthBrightnessFactor: 1.0,
    sun: {
      surface: {
        coreBoost: 1.28,
        rimPower: 2.05,
        noiseScale: 7.2,
        intensityBase: 1.08,
        intensityBoost: 1.02,
      },
      glow: {
        innerScale: 7.4,
        coronaScale: 10.8,
        raysScale: 13.4,
        haloScale: 26.0,
        outerScale: 31.5,
        innerOpacityBase: 0.92,
        coronaOpacityBase: 0.6,
        raysOpacityBase: 0.46,
        haloOpacityBase: 0.4,
        outerOpacityBase: 0.2,
        innerOpacityBoost: 0.16,
        coronaOpacityBoost: 0.16,
        raysOpacityBoost: 0.16,
        haloOpacityBoost: 0.22,
        outerOpacityBoost: 0.18,
        raysScaleBoost: 0.045,
        haloScaleBoost: 0.05,
        outerScaleBoost: 0.055,
      },
      offsets: {
        inner: 0.18,
        corona: 0.12,
        rays: 0.06,
        halo: 0.04,
        outer: 0.02,
      },
      opacityCaps: {
        inner: 0.98,
        corona: 0.82,
        rays: 0.72,
        halo: 0.64,
        outer: 0.42,
      },
    },
    atmosphere: {
      hazeStrength: 0.34,
      dayEdge: 0.92,
      sunHaloIntensity: 0.2,
      sunHaloTightness: 14.0,
      alphaMax: 0.2,
    },
  },
  {
    id: "hybrid",
    label: "Hybrid",
    distance: 140,
    visualRadius: 1.08,
    directionalLightBase: 3.8,
    ambientIntensity: 0.6,
    toneMappingExposure: 1.2,
    earthBrightnessFactor: 0.95,
    sun: {
      surface: {
        coreBoost: 1.23,
        rimPower: 1.88,
        noiseScale: 6.9,
        intensityBase: 1.15,
        intensityBoost: 1.18,
      },
      glow: {
        innerScale: 7.2,
        coronaScale: 10.2,
        raysScale: 13.0,
        haloScale: 21.5,
        outerScale: 26.0,
        innerOpacityBase: 0.9,
        coronaOpacityBase: 0.6,
        raysOpacityBase: 0.5,
        haloOpacityBase: 0.34,
        outerOpacityBase: 0.17,
        innerOpacityBoost: 0.18,
        coronaOpacityBoost: 0.18,
        raysOpacityBoost: 0.2,
        haloOpacityBoost: 0.24,
        outerOpacityBoost: 0.18,
        raysScaleBoost: 0.05,
        haloScaleBoost: 0.045,
        outerScaleBoost: 0.05,
      },
      offsets: {
        inner: 0.18,
        corona: 0.12,
        rays: 0.06,
        halo: 0.04,
        outer: 0.02,
      },
      opacityCaps: {
        inner: 0.99,
        corona: 0.84,
        rays: 0.76,
        halo: 0.62,
        outer: 0.4,
      },
    },
    atmosphere: {
      hazeStrength: 0.42,
      dayEdge: 0.9,
      sunHaloIntensity: 0.14,
      sunHaloTightness: 10.0,
      alphaMax: 0.23,
    },
  },
  {
    id: "cinematic",
    label: "Cinematic",
    distance: 120,
    visualRadius: 1.3,
    directionalLightBase: 4.4,
    ambientIntensity: 0.75,
    toneMappingExposure: 1.28,
    earthBrightnessFactor: 1.1,
    sun: {
      surface: {
        coreBoost: 1.34,
        rimPower: 1.78,
        noiseScale: 6.6,
        intensityBase: 1.2,
        intensityBoost: 1.3,
      },
      glow: {
        innerScale: 7.6,
        coronaScale: 10.8,
        raysScale: 14.2,
        haloScale: 23.0,
        outerScale: 28.5,
        innerOpacityBase: 0.92,
        coronaOpacityBase: 0.62,
        raysOpacityBase: 0.54,
        haloOpacityBase: 0.4,
        outerOpacityBase: 0.22,
        innerOpacityBoost: 0.2,
        coronaOpacityBoost: 0.2,
        raysOpacityBoost: 0.22,
        haloOpacityBoost: 0.28,
        outerOpacityBoost: 0.22,
        raysScaleBoost: 0.055,
        haloScaleBoost: 0.05,
        outerScaleBoost: 0.055,
      },
      offsets: {
        inner: 0.18,
        corona: 0.12,
        rays: 0.06,
        halo: 0.04,
        outer: 0.02,
      },
      opacityCaps: {
        inner: 1.0,
        corona: 0.88,
        rays: 0.82,
        halo: 0.7,
        outer: 0.48,
      },
    },
    atmosphere: {
      hazeStrength: 0.5,
      dayEdge: 0.88,
      sunHaloIntensity: 0.18,
      sunHaloTightness: 8.0,
      alphaMax: 0.26,
    },
  },
];

export const SUN_PRESETS = Object.fromEntries(
  SUN_PRESET_OPTIONS.map((preset) => [preset.id, Object.freeze(preset)]),
);

export const DEFAULT_SUN_PRESET_ID = "realistic";

export const DEFAULT_SUN_PRESET = SUN_PRESETS[DEFAULT_SUN_PRESET_ID];

export function getSunPreset(presetId) {
  return SUN_PRESETS[presetId] ?? DEFAULT_SUN_PRESET;
}
